# Dicionário de Tradução:
# Crie um dicionário de tradução que mapeie palavras de um idioma para outro (por exemplo, inglês para português). 
# Peça ao usuário para inserir uma palavra em inglês e, em seguida, imprima a tradução correspondente.

# 200 Palavras

# Dicionário de tradução: inglês -> português (200 palavras)

traducao = {
    "apple": "maçã",
    "banana": "banana",
    "orange": "laranja",
    "grape": "uva",
    "pineapple": "abacaxi",
    "car": "carro",
    "house": "casa",
    "dog": "cachorro",
    "cat": "gato",
    "book": "livro",
    "pen": "caneta",
    "pencil": "lápis",
    "table": "mesa",
    "chair": "cadeira",
    "window": "janela",
    "door": "porta",
    "computer": "computador",
    "phone": "telefone",
    "keyboard": "teclado",
    "mouse": "mouse",
    "monitor": "monitor",
    "television": "televisão",
    "bed": "cama",
    "pillow": "travesseiro",
    "blanket": "cobertor",
    "shirt": "camisa",
    "pants": "calça",
    "shoes": "sapatos",
    "hat": "chapéu",
    "jacket": "jaqueta",
    "coat": "casaco",
    "glasses": "óculos",
    "watch": "relógio",
    "bag": "bolsa",
    "wallet": "carteira",
    "money": "dinheiro",
    "bank": "banco",
    "market": "mercado",
    "store": "loja",
    "school": "escola",
    "university": "universidade",
    "teacher": "professor",
    "student": "aluno",
    "class": "aula",
    "lesson": "lição",
    "question": "pergunta",
    "answer": "resposta",
    "language": "idioma",
    "dictionary": "dicionário",
    "paper": "papel",
    "notebook": "caderno",
    "food": "comida",
    "water": "água",
    "milk": "leite",
    "bread": "pão",
    "butter": "manteiga",
    "cheese": "queijo",
    "egg": "ovo",
    "meat": "carne",
    "fish": "peixe",
    "chicken": "frango",
    "rice": "arroz",
    "beans": "feijão",
    "soup": "sopa",
    "salad": "salada",
    "fruit": "fruta",
    "vegetable": "vegetal",
    "sugar": "açúcar",
    "salt": "sal",
    "pepper": "pimenta",
    "oil": "óleo",
    "coffee": "café",
    "tea": "chá",
    "juice": "suco",
    "beer": "cerveja",
    "wine": "vinho",
    "breakfast": "café da manhã",
    "lunch": "almoço",
    "dinner": "jantar",
    "snack": "lanche",
    "family": "família",
    "father": "pai",
    "mother": "mãe",
    "brother": "irmão",
    "sister": "irmã",
    "son": "filho",
    "daughter": "filha",
    "friend": "amigo",
    "man": "homem",
    "woman": "mulher",
    "child": "criança",
    "baby": "bebê",
    "day": "dia",
    "night": "noite",
    "morning": "manhã",
    "afternoon": "tarde",
    "evening": "entardecer",
    "today": "hoje",
    "tomorrow": "amanhã",
    "yesterday": "ontem",
    "time": "tempo",
    "hour": "hora",
    "minute": "minuto",
    "second": "segundo",
    "week": "semana",
    "month": "mês",
    "year": "ano",
    "sun": "sol",
    "moon": "lua",
    "star": "estrela",
    "sky": "céu",
    "rain": "chuva",
    "snow": "neve",
    "wind": "vento",
    "storm": "tempestade",
    "cloud": "nuvem",
    "tree": "árvore",
    "flower": "flor",
    "grass": "grama",
    "leaf": "folha",
    "river": "rio",
    "lake": "lago",
    "sea": "mar",
    "ocean": "oceano",
    "mountain": "montanha",
    "valley": "vale",
    "forest": "floresta",
    "desert": "deserto",
    "island": "ilha",
    "city": "cidade",
    "town": "vilarejo",
    "village": "aldeia",
    "country": "país",
    "road": "estrada",
    "street": "rua",
    "bridge": "ponte",
    "car": "carro",
    "bus": "ônibus",
    "train": "trem",
    "plane": "avião",
    "bicycle": "bicicleta",
    "motorcycle": "motocicleta",
    "boat": "barco",
    "ship": "navio",
    "airport": "aeroporto",
    "station": "estação",
    "hotel": "hotel",
    "restaurant": "restaurante",
    "hospital": "hospital",
    "pharmacy": "farmácia",
    "police": "polícia",
    "firefighter": "bombeiro",
    "doctor": "médico",
    "nurse": "enfermeira",
    "engineer": "engenheiro",
    "lawyer": "advogado",
    "worker": "trabalhador",
    "job": "trabalho",
    "work": "trabalhar",
    "money": "dinheiro",
    "price": "preço",
    "cheap": "barato",
    "expensive": "caro",
    "big": "grande",
    "small": "pequeno",
    "long": "longo",
    "short": "curto",
    "fast": "rápido",
    "slow": "lento",
    "hot": "quente",
    "cold": "frio",
    "happy": "feliz",
    "sad": "triste",
    "angry": "bravo",
    "tired": "cansado",
    "beautiful": "bonito",
    "ugly": "feio",
    "good": "bom",
    "bad": "ruim",
    "yes": "sim",
    "no": "não",
    "please": "por favor",
    "thank you": "obrigado",
    "sorry": "desculpe",
    "hello": "olá",
    "goodbye": "adeus"
}


palavra = input("Digite uma palavra em inglês para traduzir: ").lower()

if palavra in traducao:
    print(f"A tradução de '{palavra}' é: {traducao[palavra]}")
else:
    print(f"A palavra '{palavra}' não está no dicionário.")
